version: '3.8'

services:
    # Traefik reverse proxy for localised domains
    traefik:
        image: traefik:v2.5
        container_name: traefik
        command:
            - --api.insecure=true
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false
            - --entrypoints.web.address=:80
        ports:
            - 80:80
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro

    # PostgreSQL database container
    postgres:
        container_name: postgres
        image: postgres:13-alpine
        ports:
            - 127.0.0.1:5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            # Database name
            POSTGRES_DB: wavechat
            # Database password
            POSTGRES_PASSWORD: pgadmin
        depends_on:
            - traefik

    # WaveChat Api container (Backend)
    api:
        container_name: api
        build:
            context: ./api
            target: development
        working_dir: /api
        command: pnpm dev
        volumes:
            - ./api:/api:rw
        ports:
            - 127.0.0.1:5000:5000
            - 127.0.0.1:5001:5001
        depends_on:
            - traefik
            - postgres
        labels:
            - traefik.enable=true
            - traefik.http.routers.api.entrypoints=web
            - traefik.http.routers.api.rule=Host(`api.wavechat.localhost`)

    # WaveChat Web app container (Frontend)
    web:
        container_name: web
        build:
            context: ./web
            target: development
        working_dir: /web
        command: pnpm dev
        volumes:
            - ./web:/web:rw
        ports:
            - 127.0.0.1:3000:3000
        depends_on:
            - traefik
            - postgres
            - api
        labels:
            - traefik.enable=true
            - traefik.http.routers.web.entrypoints=web
            - traefik.http.routers.web.rule=Host(`web.wavechat.localhost`)

    # Codegen - GraphQL code generator for ApolloClient (Frontend)
    codegen:
        container_name: codegen
        build:
            context: ./web
            target: development
        working_dir: /web
        command: pnpm codegen
        network_mode: host
        volumes:
            - ./web:/web:rw
        depends_on:
            - traefik
            - postgres
            - api
            - web

# Volume for PostgreSQL database to persist data between development sessions
volumes:
    pgdata: {}
