version: '3.8'

services:
    # PostgreSQL database container
    postgres:
        container_name: postgres
        image: postgres:13.3-alpine
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            # Database name
            POSTGRES_DB: wavechat
            # Database password
            POSTGRES_PASSWORD: pgadmin

    # WaveChat Api container (Backend)
    api:
        container_name: api
        build: ./api
        working_dir: /api
        command: pnpm dev
        volumes:
            - ./api:/api:rw
        ports:
            - 5000:5000
            - 5001:5001
        depends_on:
            - postgres

    # WaveChat Web app container (Frontend)
    web:
        container_name: web
        build: ./web
        working_dir: /web
        command: pnpm dev
        volumes:
            - ./web:/web:rw
        ports:
            - 3000:3000
        depends_on:
            - postgres
            - api

    # Codegen - GraphQL code generator for ApolloClient (Frontend)
    codegen:
        container_name: codegen
        build: ./web
        working_dir: /web
        command: pnpm codegen
        network_mode: host
        volumes:
            - ./web:/web:rw
        depends_on:
            - postgres
            - api
            - web

# Volume for PostgreSQL database to persist data between development sessions
volumes:
    pgdata: {}
