version: '3.8'

services:
    # Traefik reverse proxy for local domains + load balancing
    traefik-prod:
        # container_name: wave-traefik-prod
        image: traefik:v2.5
        command:
            - --api.insecure=true
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false
            - --entrypoints.wave.address=:80
        ports:
            - 80:80
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro

    # PostgreSQL database container
    postgres-prod:
        # container_name: wave-postgres-prod
        image: postgres:13-alpine
        ports:
            - 5432:5432
        volumes:
            - pgdata-prod:/var/lib/postgresql/data
        environment:
            # Database name
            POSTGRES_DB: wavechat
            # Database password
            POSTGRES_PASSWORD: pgadmin

    # WaveChat Api container (Backend)
    api-prod:
        # container_name: wave-api-prod
        build:
            context: ./api
            dockerfile: ./prod.Dockerfile
            target: production
        working_dir: /api
        restart: on-failure
        depends_on:
            - traefik-prod
            - postgres-prod
        labels:
            - traefik.enable=true
            - traefik.http.routers.api.entrypoints=wave
            # Web route prefixed with specific routes gets forwarded to api
            - traefik.http.routers.api.rule=Host(`wavechat.localhost`) && PathPrefix(`/graphql`) || PathPrefix(`/ws`)

    # WaveChat Web app container (Frontend)
    web-prod:
        # container_name: wave-web-prod
        build:
            context: ./web
            dockerfile: ./prod.Dockerfile
            target: production
        working_dir: /web
        restart: on-failure
        depends_on:
            - traefik-prod
            - postgres-prod
            - api-prod
        labels:
            - traefik.enable=true
            - traefik.http.routers.web.entrypoints=wave
            # Web route other than api routes gets forwarded to api
            - traefik.http.routers.web.rule=Host(`wavechat.localhost`)

# Volume for PostgreSQL database to persist data between development sessions
volumes:
    pgdata-prod: {}
