version: '3.8'

services:
    postgres:
        container_name: postgres
        image: postgres:13.3-alpine
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: wavechat
            POSTGRES_PASSWORD: pgadmin

    server:
        container_name: server
        image: node:16
        working_dir: /app/server
        command: yarn --cwd server dev
        volumes:
            - .:/app/server:rw
        ports:
            - 5000:5000
            - 5001:5001
        depends_on:
            - postgres
        environment:
            NODE_ENV: development
            PORT: 5000
            DATABASE_URL: postgresql://postgres:pgadmin@postgres:5432/wavechat?schema=public
            ADMIN_PASS: admin00
            JWT_SECRET: verysecretkey

    client:
        container_name: client
        image: node:16
        working_dir: /app/client
        command: yarn --cwd client dev
        volumes:
            - .:/app/client:rw
        ports:
            - 3000:3000
        depends_on:
            - postgres
            - server

    codegen:
        container_name: codegen
        image: node:16
        working_dir: /app
        command: yarn --cwd client codegen
        network_mode: host
        volumes:
            - .:/app:rw
        depends_on:
            - postgres
            - server
            - client

volumes:
    pgdata: {}
